name = "public-sales-decision-os-lp"
compatibility_date = "2026-09-01"
pages_build_output_dir = "./src"

[[d1_databases]]
binding = "DB"
database_name = "public-sales-lp"
database_id = "40497a74-3492-4cab-8366-23f09c440954"
