import test from 'node:test';
import assert from 'node:assert/strict';
import { verifyGitHubOidc, validateClaims, bearerToken, DEFAULT_EXPECTED } from '../lib/github-oidc.js';

const enc=v=>Buffer.from(typeof v==='string'?v:JSON.stringify(v)).toString('base64url');
async function fixture(overrides={},headerExtra={}){const keys=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const pub=await crypto.subtle.exportKey('jwk',keys.publicKey);pub.kid='test-key';pub.alg='RS256';pub.use='sig';const now=Math.floor(Date.now()/1000);const header={alg:'RS256',typ:'JWT',kid:'test-key',...headerExtra};const payload={iss:DEFAULT_EXPECTED.issuer,aud:DEFAULT_EXPECTED.audience,repository:DEFAULT_EXPECTED.repository,ref:DEFAULT_EXPECTED.ref,workflow_ref:DEFAULT_EXPECTED.workflow_ref,iat:now-5,nbf:now-5,exp:now+300,...overrides};const signing=`${enc(header)}.${enc(payload)}`;const sig=await crypto.subtle.sign({name:'RSASSA-PKCS1-v1_5'},keys.privateKey,new TextEncoder().encode(signing));return{token:`${signing}.${Buffer.from(sig).toString('base64url')}`,jwks:{keys:[pub]},now};}
test('OIDC valid signed token passes',async()=>{const f=await fixture();const p=await verifyGitHubOidc(f.token,{jwks:f.jwks,nowSeconds:f.now});assert.equal(p.repository,DEFAULT_EXPECTED.repository);});
test('OIDC wrong audience rejected',async()=>{const f=await fixture({aud:'other'});await assert.rejects(()=>verifyGitHubOidc(f.token,{jwks:f.jwks,nowSeconds:f.now}),/OIDC_AUDIENCE/);});
test('OIDC wrong repository rejected',async()=>{const f=await fixture({repository:'other/repo'});await assert.rejects(()=>verifyGitHubOidc(f.token,{jwks:f.jwks,nowSeconds:f.now}),/OIDC_REPOSITORY/);});
test('OIDC wrong ref rejected',async()=>{const f=await fixture({ref:'refs/heads/evil'});await assert.rejects(()=>verifyGitHubOidc(f.token,{jwks:f.jwks,nowSeconds:f.now}),/OIDC_REF/);});
test('OIDC wrong workflow rejected',async()=>{const f=await fixture({workflow_ref:'other'});await assert.rejects(()=>verifyGitHubOidc(f.token,{jwks:f.jwks,nowSeconds:f.now}),/OIDC_WORKFLOW/);});
test('OIDC expired rejected',async()=>{const f=await fixture({exp:1});await assert.rejects(()=>verifyGitHubOidc(f.token,{jwks:f.jwks,nowSeconds:f.now}),/OIDC_EXPIRED/);});
test('OIDC future nbf rejected',async()=>{const f=await fixture({nbf:Math.floor(Date.now()/1000)+1000});await assert.rejects(()=>verifyGitHubOidc(f.token,{jwks:f.jwks,nowSeconds:f.now}),/OIDC_NOT_YET_VALID/);});
test('OIDC unknown key rejected',async()=>{const f=await fixture();await assert.rejects(()=>verifyGitHubOidc(f.token,{jwks:{keys:[]},nowSeconds:f.now}),/OIDC_KID/);});
test('OIDC ignores token-supplied jku',async()=>{const f=await fixture({}, {jku:'https://evil.example/jwks'});const p=await verifyGitHubOidc(f.token,{jwks:f.jwks,nowSeconds:f.now});assert.equal(p.ref,'refs/heads/main');});
test('OIDC tampered signature rejected',async()=>{const f=await fixture();const parts=f.token.split('.');parts[1]=enc({...JSON.parse(Buffer.from(parts[1],'base64url').toString()),repository:'evil/repo'});await assert.rejects(()=>verifyGitHubOidc(parts.join('.'),{jwks:f.jwks,nowSeconds:f.now}),/OIDC_SIGNATURE/);});
test('claim validator accepts audience array',()=>{const now=Math.floor(Date.now()/1000);assert.equal(validateClaims({iss:DEFAULT_EXPECTED.issuer,aud:['x',DEFAULT_EXPECTED.audience],repository:DEFAULT_EXPECTED.repository,ref:DEFAULT_EXPECTED.ref,workflow_ref:DEFAULT_EXPECTED.workflow_ref,iat:now,exp:now+10},DEFAULT_EXPECTED,now),true);});
test('bearer token parser is strict',()=>{assert.equal(bearerToken(new Request('https://x',{headers:{authorization:'Bearer abc.def.ghi'}})),'abc.def.ghi');assert.equal(bearerToken(new Request('https://x',{headers:{authorization:'Basic x'}})),null);});
