import { requireClientKey } from '../../lib/client-token.js';
import { recordEvent } from '../../lib/events.js';
import { cleanText, json, readJson } from '../../lib/validation.js';
const EMP=new Set(['1-4','5-9','10-30','31-99','100+','']);
const SIZE=new Set(['small','medium','large','undecided','']);
const EXP=new Set(['none','considering','once_or_more']);
const QUAL=new Set(['yes','no','unknown']);
function sanitize(b){const regions=Array.isArray(b.regions)?b.regions.map(x=>cleanText(x,50)).filter(Boolean).slice(0,20):[];return{company_name:cleanText(b.company_name,120),industry:cleanText(b.industry,80),services:cleanText(b.services,1000),regions,employee_scale:cleanText(b.employee_scale,20),desired_project_size:cleanText(b.desired_project_size,20),public_experience:cleanText(b.public_experience,30),unified_qualification:cleanText(b.unified_qualification,20),strengths:cleanText(b.strengths,1000)};}
function valid(p){return Boolean(p.company_name&&p.industry&&p.services.length>=2&&p.regions.length&&EMP.has(p.employee_scale)&&SIZE.has(p.desired_project_size)&&EXP.has(p.public_experience)&&QUAL.has(p.unified_qualification));}
export async function onRequestGet({request,env}){const k=await requireClientKey(request);if(!k)return json({ok:false,error:'TOKEN_REQUIRED'},400);const r=await env.DB.prepare('SELECT * FROM company_profiles WHERE client_key=?').bind(k).first();if(!r)return json({ok:true,profile:null});return json({ok:true,profile:{company_name:r.company_name,industry:r.industry,services:r.services,regions:JSON.parse(r.regions_json||'[]'),employee_scale:r.employee_scale,desired_project_size:r.desired_project_size,public_experience:r.public_experience,unified_qualification:r.unified_qualification,strengths:r.strengths}});}
export async function onRequestPut({request,env}){const k=await requireClientKey(request);if(!k)return json({ok:false,error:'TOKEN_REQUIRED'},400);let b;try{b=await readJson(request);}catch(e){return json({ok:false,error:e.message},e.status||400);}const p=sanitize(b);if(!valid(p))return json({ok:false,error:'INVALID_INPUT'},400);const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO company_profiles(client_key,company_name,industry,services,regions_json,employee_scale,desired_project_size,public_experience,unified_qualification,strengths,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(client_key) DO UPDATE SET company_name=excluded.company_name,industry=excluded.industry,services=excluded.services,regions_json=excluded.regions_json,employee_scale=excluded.employee_scale,desired_project_size=excluded.desired_project_size,public_experience=excluded.public_experience,unified_qualification=excluded.unified_qualification,strengths=excluded.strengths,updated_at=excluded.updated_at`).bind(k,p.company_name,p.industry,p.services,JSON.stringify(p.regions),p.employee_scale||null,p.desired_project_size||null,p.public_experience,p.unified_qualification,p.strengths||null,now,now).run();try{await recordEvent(env.DB,{event_type:'company_profile_complete',session_id:cleanText(request.headers.get('x-session-id'),80)||'anonymous',client_key:k,entity_type:'profile'});}catch{}return json({ok:true});}
export async function onRequestDelete({request,env}){const k=await requireClientKey(request);if(!k)return json({ok:false,error:'TOKEN_REQUIRED'},400);await env.DB.batch([env.DB.prepare('DELETE FROM watch_items WHERE client_key=?').bind(k),env.DB.prepare('DELETE FROM recent_views WHERE client_key=?').bind(k),env.DB.prepare('DELETE FROM search_history WHERE client_key=?').bind(k),env.DB.prepare('DELETE FROM company_profiles WHERE client_key=?').bind(k),env.DB.prepare('UPDATE events SET client_key=NULL WHERE client_key=?').bind(k)]);return json({ok:true});}
export const __test={sanitize,valid};
