import { matchOpportunity } from './matcher.js';
import { publicOpportunity, safeJson } from './db.js';

const TECH_TAGS = [['AI',/(^|[^A-Za-z0-9])AI([^A-Za-z0-9]|$)|生成AI|人工知能/i],['Web',/(^|[^A-Za-z0-9])Web([^A-Za-z0-9]|$)|ウェブ/i],['DX',/(^|[^A-Za-z0-9])DX([^A-Za-z0-9]|$)/i],['RPA',/(^|[^A-Za-z0-9])RPA([^A-Za-z0-9]|$)/i],['SaaS',/(^|[^A-Za-z0-9])SaaS([^A-Za-z0-9]|$)/i]];
const FINGERPRINT_FIELDS=['title','organization_name','prefecture_code','prefecture_name','city_name','location','announced_at','category','procedure_type','certification','description','source_url','attachments_json','tender_submission_raw','opening_event_raw','period_end_raw','deadline_at','deadline_source','source_status'];
function fnv1a(text){let h=0x811c9dc5;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,0x01000193)>>>0;}return h.toString(16).padStart(8,'0');}
export function sourceFingerprint(row){const canonical=FINGERPRINT_FIELDS.map(k=>`${k}=${String(row?.[k]??'')}`).join('\n');return fnv1a(canonical);}
export function matchBand(decision){if(!decision)return null;if(decision.decision==='GO')return'high';if(decision.decision==='WATCH')return'medium';return'low';}
export function hasWatchUpdate(row){return Boolean(row?.source_hash_snapshot&&row?.title&&row.source_hash_snapshot!==sourceFingerprint(row));}
export function profileCompletion(profile){if(!profile)return{percent:0,missing_fields:['company_name','industry','services','regions','employee_scale','desired_project_size','public_experience','unified_qualification','strengths']};const values={company_name:profile.company_name,industry:profile.industry,services:profile.services,regions:Array.isArray(profile.regions)?profile.regions:safeJson(profile.regions_json,[]),employee_scale:profile.employee_scale,desired_project_size:profile.desired_project_size,public_experience:profile.public_experience,unified_qualification:profile.unified_qualification,strengths:profile.strengths};const filled=Object.entries(values).filter(([k,v])=>k==='regions'?Array.isArray(v)&&v.length>0:String(v??'').trim()!==''&&v!=='unknown'&&v!=='undecided');const missing_fields=Object.keys(values).filter(k=>!filled.some(([f])=>f===k));const percent=Math.round(((filled.length/Object.keys(values).length)*100)/5)*5;return{percent:Math.min(100,Math.max(0,percent)),missing_fields};}
export function featureTags(row,decision,updated=false,now=new Date()){const tags=[];if(updated)tags.push('更新あり');if(row.announced_at){const age=(now-new Date(`${row.announced_at}T00:00:00Z`))/86400000;if(age>=0&&age<=7)tags.push('新着');}const primary=`${row.title||''}\n${String(row.description||'').slice(0,600)}`;if(decision?.service_relevant){for(const[label,re]of TECH_TAGS)if(re.test(primary))tags.push(label);}if(row.certification)tags.push('資格要件あり');if(decision?.positive_reasons?.some(x=>x.includes('対応地域と一致')))tags.push('地域一致');return[...new Set(tags)].slice(0,6);}
export function opportunityViewModel(row,profile=null,watchRow=null){const decision=profile?matchOpportunity(profile,row):null;const updated=hasWatchUpdate(watchRow?{...row,source_hash_snapshot:watchRow.source_hash_snapshot}:row);return{source:publicOpportunity(row),decision,match_band:matchBand(decision),watched:Boolean(watchRow),has_update:updated,feature_tags:featureTags(row,decision,updated),reason_summary:(decision?.positive_reasons||[]).slice(0,2),check_summary:(decision?.check_points||[]).slice(0,2)};}
export function sortViewModels(items,sort='default'){const out=[...items];if(sort==='fit')return out.sort((a,b)=>(b.decision?.score??-1)-(a.decision?.score??-1));if(sort==='new')return out.sort((a,b)=>String(b.source.announced_at||'').localeCompare(String(a.source.announced_at||'')));if(sort==='deadline')return out.sort((a,b)=>{const ad=a.source.deadline_at,bd=b.source.deadline_at;if(!ad&&!bd)return 0;if(!ad)return 1;if(!bd)return-1;return String(ad).localeCompare(String(bd));});return out;}
export const __test={FINGERPRINT_FIELDS,fnv1a};
