const state={route:'home',searchItems:[],watchIds:new Set(),profile:null,lastQuery:'AI'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function newToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
function token(){let t=localStorage.getItem('public_sales_client_token');if(!t){t=newToken();localStorage.setItem('public_sales_client_token',t);}return t;}
function session(){let s=sessionStorage.getItem('public_sales_sid');if(!s){s=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;sessionStorage.setItem('public_sales_sid',s);}return s;}
async function api(path,opts={}){const headers={'X-Client-Token':token(),'X-Session-Id':session(),...(opts.headers||{})};if(opts.body&&!headers['content-type'])headers['content-type']='application/json';const r=await fetch(path,{...opts,headers});let d={};try{d=await r.json();}catch{}if(!r.ok)throw new Error(d.message||d.error||`HTTP ${r.status}`);return d;}
async function track(event_type,extra={}){try{await api('/api/event',{method:'POST',body:JSON.stringify({event_type,session_id:session(),path:location.pathname,entity_type:extra.entity_type,entity_id:extra.entity_id,metadata:extra.metadata})});}catch{}}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined&&text!==null)e.textContent=String(text);if(cls)e.className=cls;return e;}
function clear(node){node.replaceChildren();}
function empty(node,text){clear(node);node.append(el('div',text,'empty'));}
function fmtDate(v){if(!v)return '情報なし';const d=new Date(`${v}T00:00:00`);return Number.isNaN(d)?v:new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium'}).format(d);}
function region(o){return [o.prefecture_name,o.city_name,o.location].filter(Boolean).join(' / ')||'情報なし';}
function decisionBadge(d){if(!d)return null;return el('span',d.decision,`badge ${d.decision.toLowerCase()}`);}
function route(name,id=null){state.route=name;$$('.view').forEach(v=>v.hidden=v.id!==`view-${name}`);$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===name));history.replaceState(null,'',name==='detail'&&id?`#detail=${id}`:`#${name}`);scrollTo({top:0,behavior:'smooth'});if(name==='home')loadHome();if(name==='watch')loadWatch();if(name==='profile')loadProfile();if(name==='detail'&&id)loadDetail(id);}
$$('[data-route]').forEach(b=>b.addEventListener('click',()=>route(b.dataset.route)));
function opportunityCard(item,decision=null,watched=false){const c=el('article',null,'op-card');const top=el('div',null,'top'),main=el('div'),side=el('div');const badges=el('div',null,'badges');if(item.announced_at&&Date.now()-new Date(`${item.announced_at}T00:00:00Z`)<7*86400000)badges.append(el('span','新着','badge new'));const db=decisionBadge(decision);if(db)badges.append(db);main.append(badges,el('h3',item.title||'案件名なし'));const meta=el('div',null,'meta');for(const x of [item.organization_name||'発注機関情報なし',region(item),`公告日/取得日: ${fmtDate(item.announced_at)}`,item.deadline_at?`締切: ${fmtDate(item.deadline_at)}`:'期限: 原典で確認',item.procedure_type,item.category].filter(Boolean))meta.append(el('span',x));main.append(meta);const wb=el('button',watched?'★ WATCH中':'☆ WATCH','watch-btn');wb.type='button';wb.addEventListener('click',async()=>{try{if(watched){await api(`/api/watch/${encodeURIComponent(item.id)}`,{method:'DELETE'});state.watchIds.delete(item.id);watched=false;wb.textContent='☆ WATCH';}else{await api('/api/watch',{method:'POST',body:JSON.stringify({opportunity_id:item.id})});state.watchIds.add(item.id);watched=true;wb.textContent='★ WATCH中';}}catch(e){alert(`WATCHを更新できません: ${e.message}`);}});side.append(wb);top.append(main,side);c.append(top);const actions=el('div',null,'card-actions');const detail=el('button','詳細を見る','primary');detail.type='button';detail.addEventListener('click',()=>route('detail',item.id));actions.append(detail);if(item.source_url){const a=el('a','原典を開く','secondary');a.href=item.source_url;a.target='_blank';a.rel='noopener noreferrer';actions.append(a);}c.append(actions);return c;}
function mini(node,items){clear(node);if(!items?.length){node.append(el('div','まだ表示できる案件がありません。','empty'));return;}for(const x of items){const row=el('div',null,'mini-item');const item=x.source||x,b=el('button',item.title);b.addEventListener('click',()=>route('detail',item.id));row.append(b);node.append(row);}}
async function loadHome(){try{const d=await api('/api/home');const banner=$('#profile-banner');if(d.profile_status==='missing'){banner.hidden=false;clear(banner);banner.append(el('strong','プロフィールを作るとおすすめ案件を表示できます。'));const b=el('button','プロフィールを作る','secondary');b.addEventListener('click',()=>route('profile'));banner.append(b);}else banner.hidden=true;const rec=$('#home-recommendations');clear(rec);if(d.recommendations?.length){for(const x of d.recommendations)rec.append(opportunityCard(x.source,x.decision,state.watchIds.has(x.source.id)));}else empty(rec,'プロフィールを保存し、案件データが集まるとおすすめを表示します。');mini($('#home-new'),d.new_items);mini($('#home-deadline'),d.deadline_items);mini($('#home-watch'),d.watch_items);const tasks=$('#home-actions');clear(tasks);if(d.today_actions?.length)for(const t of d.today_actions){const x=el('div',null,'task');x.append(el('strong',t.action),el('div',t.title));x.addEventListener('click',()=>route('detail',t.opportunity_id));tasks.append(x);}else empty(tasks,'今日の優先タスクはまだありません。');}catch(e){empty($('#home-recommendations'),`読み込みに失敗しました: ${e.message}`);}}
$('#search-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),p=new URLSearchParams();for(const [k,v] of fd){if(v)p.set(k,v);}state.lastQuery=p.get('q')||'';$('#search-status').textContent='検索中…';try{const d=await api(`/api/opportunities/search?${p}`);state.searchItems=d.items||[];$('#search-status').textContent=`検索結果 ${d.count}件${d.cache?.stale?'（キャッシュ表示）':''}`;renderSearch();}catch(err){$('#search-status').textContent=`検索できませんでした: ${err.message}`;empty($('#search-results'),'条件を変えるか、時間をおいてもう一度お試しください。');}});
function renderSearch(){const root=$('#search-results');clear(root);if(!state.searchItems.length){empty(root,'該当案件がありません。別のキーワードも試してください。');return;}for(const item of state.searchItems)root.append(opportunityCard(item,null,state.watchIds.has(item.id)));}
async function loadDetail(id){const root=$('#detail-root');empty(root,'読み込み中…');try{const d=await api(`/api/opportunities/${encodeURIComponent(id)}`);clear(root);const s=d.source,hero=el('section',null,'detail-hero');const badges=el('div',null,'badges'),db=decisionBadge(d.decision);if(db)badges.append(db);hero.append(badges,el('h1',s.title));const meta=el('div',null,'meta');for(const x of [s.organization_name,region(s),`公告日/取得日: ${fmtDate(s.announced_at)}`,s.deadline_at?`締切: ${fmtDate(s.deadline_at)}`:'期限: 原典で確認',s.category,s.procedure_type].filter(Boolean))meta.append(el('span',x));hero.append(meta);if(s.source_url){const a=el('a','原典を開く ↗','primary');a.href=s.source_url;a.target='_blank';a.rel='noopener noreferrer';hero.append(el('div','※参加条件・期限・提出物は原典で最終確認してください。','source-note'),a);}root.append(hero);const source=el('section',null,'detail-source');source.append(el('span','公式・原典情報','badge'),el('h2','取得できた案件情報'));const grid=el('div',null,'detail-grid');const facts=[['発注機関',s.organization_name],['地域',region(s)],['公告日/取得日',fmtDate(s.announced_at)],['資格情報',s.certification||'情報なし'],['公示種別',s.procedure_type||'情報なし'],['期限',s.deadline_at?fmtDate(s.deadline_at):'原典で確認']];for(const [k,v] of facts){const f=el('div',null,'fact');f.append(el('small',k),el('strong',v));grid.append(f);}source.append(grid);if(s.description)source.append(el('p',s.description));root.append(source);const os=el('section',null,'detail-os');os.append(el('span','公共営業OSによる参考判断','badge'),el('h2',d.decision?`${d.decision.decision}｜適合度 ${d.decision.score}/100`:'プロフィール登録で自社判定できます'));if(d.decision){const cols=el('div',null,'reason-cols');for(const [title,items] of [['おすすめ理由',d.decision.positive_reasons],['要確認',d.decision.check_points],['情報不足',d.decision.missing_information]]){const box=el('div',null,'reason');box.append(el('h3',title));const ul=el('ul');for(const x of items)ul.append(el('li',x));box.append(ul);cols.append(box);}os.append(cols);}os.append(el('h3','NEXT ACTION'));const ol=el('ol');for(const a of d.next_actions||[])ol.append(el('li',a));os.append(ol,el('p',d.notice,'source-note'));root.append(os);if(d.decision)track(`${d.decision.decision.toLowerCase().replace('-','_')}_view`,{entity_type:'opportunity',entity_id:id,metadata:{score_band:Math.floor(d.decision.score/10)*10}});track('next_action_view',{entity_type:'opportunity',entity_id:id,metadata:{count:(d.next_actions||[]).length}});}catch(e){empty(root,`案件詳細を読み込めませんでした: ${e.message}`);}}
async function loadWatch(){const root=$('#watch-results');empty(root,'読み込み中…');try{const d=await api('/api/watch');state.watchIds=new Set((d.items||[]).map(x=>x.id));clear(root);if(!d.items?.length){empty(root,'WATCH中の案件はありません。案件検索から☆WATCHを押してください。');return;}for(const x of d.items)root.append(opportunityCard(x,null,true));}catch(e){empty(root,`WATCHを読み込めません: ${e.message}`);}}
async function loadProfile(){const f=$('#profile-form'),status=$('#profile-status');status.textContent='';try{const d=await api('/api/profile');state.profile=d.profile;if(!d.profile)return;for(const [k,v] of Object.entries(d.profile)){const field=f.elements[k];if(!field)continue;field.value=Array.isArray(v)?v.join(','):v??'';}}catch(e){status.textContent=`プロフィールを読み込めません: ${e.message}`;}}
$('#profile-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),body=Object.fromEntries(fd.entries());body.regions=String(body.regions||'').split(/[,、]/).map(x=>x.trim()).filter(Boolean);const status=$('#profile-status');status.textContent='保存中…';try{await api('/api/profile',{method:'PUT',body:JSON.stringify(body)});status.textContent='プロフィールを保存しました。おすすめ案件に反映します。';setTimeout(()=>route('home'),600);}catch(err){status.textContent=`保存できませんでした: ${err.message}`;}});
$('#delete-data').addEventListener('click',async()=>{if(!confirm('このブラウザに紐づく企業プロフィール・WATCH・検索/閲覧履歴を削除します。よろしいですか？'))return;try{await api('/api/profile',{method:'DELETE'});localStorage.removeItem('public_sales_client_token');state.profile=null;state.watchIds.clear();$('#profile-form').reset();$('#profile-status').textContent='無料版データを削除しました。';}catch(e){$('#profile-status').textContent=`削除できませんでした: ${e.message}`;}});
const hash=location.hash.slice(1);if(hash.startsWith('detail='))route('detail',hash.slice(7));else route(['home','search','watch','ai','profile'].includes(hash)?hash:'home');loadWatch().catch(()=>{});
